nome=input('Digite seu nome completo: ')
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}' .format(nome.upper()))
print('Seu nome em minúsculas é {}' .format(nome.lower()))
print('Seu nome tem ao todo {} letras' .format(len(nome)- nome.count(' ')))
espalha=nome.split()
print('Seu primeiro nome é {} e ele tem {} letras' .format(espalha[0], len(espalha[0])))